### ISSUE TITLE
KneeNoteの実装(データの入力画面)

### ISSUE THREAD

**Issue by yumayuma708** [yumayuma708/knee-diary#40]
## ToDo

- [x] HiltViewModelを作成し、create()メソッドを作る
- [x] UiStateをsealed interfaceで作成し、_uiStateもStateFlow()を使用して作成する
- [x] create()メソッドの中で、titleが空の場合の処理を書く
- [x] viewModelScopeの中で、create()メソッドを呼ぶ。createエラーの場合のUiStateも追加し、処理を書く
- [x] Composable側から、create()メソッドを呼ぶ
- [x] private funで関数を作り、ViewModelに依存しない画面レイアウトにする
- [x] LaunchedEffectで、inputError・createErrorの際にsnackBarが表示され、Idle状態に戻るようにする.successの時は前の画面に戻るようにする
- [x] MainModuleファイルに、DaoとDatabaseの作り方を実装する
- [x] MainModuleクラスを作成
